// ─── ISO 3166-1 alpha-2 страны для выбора территорий релиза ─────────────────
// Используется на странице «Доступность релиза» при выключенном «Весь мир».
// Названия — на русском и английском, выбор по активному языку интерфейса.

export interface Country {
  code: string; // ISO 3166-1 alpha-2
  ru: string;
  en: string;
}

export const COUNTRIES: Country[] = [
  { code: "RU", ru: "Россия", en: "Russia" },
  { code: "TJ", ru: "Таджикистан", en: "Tajikistan" },
  { code: "UZ", ru: "Узбекистан", en: "Uzbekistan" },
  { code: "KZ", ru: "Казахстан", en: "Kazakhstan" },
  { code: "KG", ru: "Киргизия", en: "Kyrgyzstan" },
  { code: "TM", ru: "Туркменистан", en: "Turkmenistan" },
  { code: "AZ", ru: "Азербайджан", en: "Azerbaijan" },
  { code: "AM", ru: "Армения", en: "Armenia" },
  { code: "GE", ru: "Грузия", en: "Georgia" },
  { code: "BY", ru: "Беларусь", en: "Belarus" },
  { code: "UA", ru: "Украина", en: "Ukraine" },
  { code: "MD", ru: "Молдавия", en: "Moldova" },
  { code: "US", ru: "США", en: "United States" },
  { code: "CA", ru: "Канада", en: "Canada" },
  { code: "MX", ru: "Мексика", en: "Mexico" },
  { code: "BR", ru: "Бразилия", en: "Brazil" },
  { code: "AR", ru: "Аргентина", en: "Argentina" },
  { code: "CL", ru: "Чили", en: "Chile" },
  { code: "CO", ru: "Колумбия", en: "Colombia" },
  { code: "PE", ru: "Перу", en: "Peru" },
  { code: "GB", ru: "Великобритания", en: "United Kingdom" },
  { code: "IE", ru: "Ирландия", en: "Ireland" },
  { code: "FR", ru: "Франция", en: "France" },
  { code: "DE", ru: "Германия", en: "Germany" },
  { code: "ES", ru: "Испания", en: "Spain" },
  { code: "PT", ru: "Португалия", en: "Portugal" },
  { code: "IT", ru: "Италия", en: "Italy" },
  { code: "NL", ru: "Нидерланды", en: "Netherlands" },
  { code: "BE", ru: "Бельгия", en: "Belgium" },
  { code: "CH", ru: "Швейцария", en: "Switzerland" },
  { code: "AT", ru: "Австрия", en: "Austria" },
  { code: "PL", ru: "Польша", en: "Poland" },
  { code: "CZ", ru: "Чехия", en: "Czechia" },
  { code: "SK", ru: "Словакия", en: "Slovakia" },
  { code: "HU", ru: "Венгрия", en: "Hungary" },
  { code: "RO", ru: "Румыния", en: "Romania" },
  { code: "BG", ru: "Болгария", en: "Bulgaria" },
  { code: "GR", ru: "Греция", en: "Greece" },
  { code: "SE", ru: "Швеция", en: "Sweden" },
  { code: "NO", ru: "Норвегия", en: "Norway" },
  { code: "DK", ru: "Дания", en: "Denmark" },
  { code: "FI", ru: "Финляндия", en: "Finland" },
  { code: "IS", ru: "Исландия", en: "Iceland" },
  { code: "EE", ru: "Эстония", en: "Estonia" },
  { code: "LV", ru: "Латвия", en: "Latvia" },
  { code: "LT", ru: "Литва", en: "Lithuania" },
  { code: "HR", ru: "Хорватия", en: "Croatia" },
  { code: "RS", ru: "Сербия", en: "Serbia" },
  { code: "SI", ru: "Словения", en: "Slovenia" },
  { code: "TR", ru: "Турция", en: "Turkey" },
  { code: "IL", ru: "Израиль", en: "Israel" },
  { code: "SA", ru: "Саудовская Аравия", en: "Saudi Arabia" },
  { code: "AE", ru: "ОАЭ", en: "United Arab Emirates" },
  { code: "QA", ru: "Катар", en: "Qatar" },
  { code: "KW", ru: "Кувейт", en: "Kuwait" },
  { code: "EG", ru: "Египет", en: "Egypt" },
  { code: "MA", ru: "Марокко", en: "Morocco" },
  { code: "DZ", ru: "Алжир", en: "Algeria" },
  { code: "TN", ru: "Тунис", en: "Tunisia" },
  { code: "ZA", ru: "ЮАР", en: "South Africa" },
  { code: "NG", ru: "Нигерия", en: "Nigeria" },
  { code: "KE", ru: "Кения", en: "Kenya" },
  { code: "GH", ru: "Гана", en: "Ghana" },
  { code: "IN", ru: "Индия", en: "India" },
  { code: "PK", ru: "Пакистан", en: "Pakistan" },
  { code: "BD", ru: "Бангладеш", en: "Bangladesh" },
  { code: "LK", ru: "Шри-Ланка", en: "Sri Lanka" },
  { code: "CN", ru: "Китай", en: "China" },
  { code: "HK", ru: "Гонконг", en: "Hong Kong" },
  { code: "TW", ru: "Тайвань", en: "Taiwan" },
  { code: "JP", ru: "Япония", en: "Japan" },
  { code: "KR", ru: "Южная Корея", en: "South Korea" },
  { code: "ID", ru: "Индонезия", en: "Indonesia" },
  { code: "MY", ru: "Малайзия", en: "Malaysia" },
  { code: "SG", ru: "Сингапур", en: "Singapore" },
  { code: "TH", ru: "Таиланд", en: "Thailand" },
  { code: "VN", ru: "Вьетнам", en: "Vietnam" },
  { code: "PH", ru: "Филиппины", en: "Philippines" },
  { code: "AU", ru: "Австралия", en: "Australia" },
  { code: "NZ", ru: "Новая Зеландия", en: "New Zealand" },
];

export function countryName(code: string, lang: "ru" | "en"): string {
  const c = COUNTRIES.find((x) => x.code === code);
  return c ? c[lang] : code;
}
