// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crm-redesign/DeepDark.tsx": () => import("../components/mockups/crm-redesign/DeepDark.tsx"),
  "./components/mockups/crm-redesign/EmeraldDark.tsx": () => import("../components/mockups/crm-redesign/EmeraldDark.tsx"),
  "./components/mockups/crm-redesign/VioletPro.tsx": () => import("../components/mockups/crm-redesign/VioletPro.tsx")
};
